Allow PluginXmlPatcher to patch multi-line tags
JetBrains/sbt-idea-plugin pull request #129
Opened 2024-05-12 15:48 UTC by zhutmost

If my plugin.xml have a multi-line tag (i.e., includes '\n') like this:
```xml
<idea-plugin>
    ...
    <description>
        determined by build.sbt
        some else
    </description>
    ...
```
the current PluginXmlPatcher cannot patch it correctly. 
The current code is:
```scala
    if (str.matches(s"(?s)^.*<$name>.+</$name>.*$$"))
        str.replaceAll(s"<$name>.+</$name>", s"<$name>$value</$name>")
    else {
       log.warn(s"$input doesn't have $name tag defined, not patching")
       ...
```
Detailed reason analysis:

The regex in the if-condition with "(?s)" enables DOTALL mode, so it can match the string with '\n'. And, the regex in the `replace` statement does not have a "(?s)", so it cannot match multiline tags, and nothing will be replaced.

2024-05-12 15:50 UTC, zhutmost commented
And I also check whether multiple tags with a same name are defined. If so, a warning will be printed and only the first one will be replaced.

That is because sometime I write comments in plugin.xml, the original version will patch all of them:

2024-05-12 19:02 UTC, unkarjedy commented
Thanks for the PR!
One final touch — please ensure the change is covered in tests.
See `org.jetbrains.sbtidea.xml.PluginXmlPatchingTest`

2024-05-13 02:51 UTC, zhutmost commented
@unkarjedy OK. but there is a small issue that the current `master` version cannot pass all the tests. The error message is that:

2024-05-13 04:24 UTC, zhutmost commented
Forgive my last comment. (I dont know what happened. After multi-runs, it looks good now.)

I have added pluginXmlPatching tests for multiple tags and duplicated tags.
But I find another critical bug that running `sbt test` will not trigger `org.jetbrains.sbtidea.xml.PluginXmlPatchingTest`. I am a newbie to SBT flow (I am a MIll user >_<) so I don't know whether the command `sbt test` is correct. (I find your CI workflow scala.yml also uses `sbt test`?)

2024-05-13 08:35 UTC, unkarjedy commented
>But I find another critical bug that running sbt test will not trigger org.jetbrains.sbtidea.xml.PluginXmlPatchingTest. I am a newbie to SBT flow (I am a MIll user >_<) so I don't know whether the command sbt test is correct. (I find your CI workflow scala.yml also uses sbt test?)

Thanks for noticing this!
Indeed, it seems like the test is ignored in SBT because it's made package private (`private class PluginXmlPatchingTest`)
No idea why it was done so.
Removing `private` helps

2024-05-13 08:44 UTC, zhutmost commented
OK, done. Looks good. You can consider merging now.

2024-05-15 08:46 UTC, unkarjedy requested changes

2024-05-15 11:37 UTC, zhutmost commented on ideaSupport/src/test/scala/org/jetbrains/sbtidea/xml/PluginXmlPatchingTest.scala
> +  test("duplicate tags are only patched the first one") {
OK. I will fix them. Just a few days (~1 week), because I've got something else going on.

2024-05-17 03:58 UTC, zhutmost commented
@unkarjedy  I have fixed your two issues. please review.

2026-07-02 14:16 UTC, unkarjedy commented
Hello!

I randomly noticed this PR which slipped my attention.
It was a ridiculously long reply, sorry for that.

I will squash the commits and merge it with your authorship preserved!

2026-07-02 17:00 UTC, closed without merging